include:
    - paytrack-postgres.yml
    - paytrack-postgrest.yml
    # - paytrack-adminer.yml

volumes:
    paytrack-postgres-data:
        name: paytrack-postgres-data

networks:
    paytrack-net:
        name: paytrack-net
        driver: bridge
