services:
    paytrack-postgrest:
        image: postgrest/postgrest:v13.0.8
        container_name: paytrack-postgrest
        restart: unless-stopped
        networks:
            - paytrack-net
        ports:
            - 4101:3000
        environment:
            PGRST_DB_URI: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@paytrack-postgres:5432/paytrack
            PGRST_DB_SCHEMA: public
            PGRST_DB_POOL: 10
            PGRST_JWT_SECRET: ${PGRST_JWT_SECRET:?environment variable PGRST_JWT_SECRET is not set.}
            PGRST_JWT_AUD: ${NEXT_PUBLIC_APP_URL:?environment variable NEXT_PUBLIC_APP_URL is not set.}
            PGRST_DB_ANON_ROLE: anon
            PGRST_DB_AUTHENTICATED_ROLE: authenticated
        depends_on:
            paytrack-postgres:
                condition: service_healthy
