services:
    paytrack-postgres:
        image: postgres:18-alpine3.22
        container_name: paytrack-postgres
        restart: unless-stopped
        init: true
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d paytrack"]
            interval: 10s
            timeout: 5s
            retries: 5
        networks:
            - paytrack-net
        volumes:
            - paytrack-postgres-data:/var/lib/postgresql
        env_file:
            - path: .env
              required: true
        ports:
            - 4100:5432
        environment:
            POSTGRES_DB: paytrack
            POSTGRES_USER: ${POSTGRES_USER:?environment variable POSTGRES_USER is not set.}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:?environment variable POSTGRES_PASSWORD is not set.}
